---
title: "Figure 4: Subnetwork of hubs and consensus score for hyper-hubs.  subplots"
output: html_notebook
author: "Alejandro Javier Acevedo Aracena, PhD - a.acevedo.aracena@gmail.com"
date: "May 24th, 2021"
---
Set paths
```{r message=FALSE, warning=FALSE}
figure <- 'Figure_4'
local_working_directory <- "~/AA_PostDoc/Acevedo_et_al_2021_neuron_astrocyte_metabolism"
file.path(local_working_directory,figure)      -> figure_folder_path
file.path(local_working_directory,'aa_functions.R') -> source_path
source(source_path)
```


#NEURON and ASTROCYTE ranked by pure genes
```{r fig.height=14, fig.width=9, message=FALSE, warning=FALSE, paged.print=FALSE}
library(clusterProfiler)
library(ReactomePA)
neuron_path <- file.path(figure_folder_path, "Neuron_IDs_centrality_optimality.csv")
get_genes_from_each_hub(neuron_path, cut_off_optimality = 0.407 , cut_off_centrality =  0.499) %>% purrr::set_names(c("Optimal", "Central", "Hyper")) -> list_of_genes_by_hubs # 
list_of_genes_by_hubs %>%compareCluster(fun='enrichPathway', pvalueCutoff=1e-4) -> neuron
neuron %>% dotplot -> c_subplot
#list_of_genes_by_hubs %>%compareCluster(fun='enrichKEGG', pvalueCutoff=1e-2)  %>% dotplot     -> e_subplot
astrocyte_path <- file.path(figure_folder_path, "Astrocyte_IDs_centrality_optimality.csv")
get_genes_from_each_hub(astrocyte_path, cut_off_optimality = 0.228 , cut_off_centrality =  0.741) %>% purrr::set_names(c("Optimal", "Central", "Hyper")) -> list_of_genes_by_hubs # 
list_of_genes_by_hubs %>%compareCluster(fun='enrichPathway', pvalueCutoff=1e-4)  -> astrocyte
astrocyte %>% dotplot-> d_subplot
#list_of_genes_by_hubs %>%compareCluster(fun='enrichKEGG', pvalueCutoff=1e-2)  %>% dotplot    -> g_subplot
ggarrange(c_subplot, d_subplot, ncol = 1, nrow = 2, labels = c('b','c')) -> dots_panel
cell_and_modules(figure_folder_path, "Neuron_IDs_centrality_optimality.csv", "Neuron",cut_off_optimality =0.407 , cut_off_centrality = 0.499 ) -> neuron_modules
cell_and_modules(figure_folder_path, "Astrocyte_IDs_centrality_optimality.csv", "Astrocyte",cut_off_optimality = 0.228, cut_off_centrality = 0.741) -> astrocyte_modules
plot_stack(neuron_modules, astrocyte_modules) -> plot.my_counts_stacked
upper_panel <- ggarrange(NULL, plot.my_counts_stacked, nrow = 1, ncol = 2, widths = c(1,.3), labels = c('a',''))
ggarrange(upper_panel, dots_panel, nrow = 2, ncol = 1, heights = c(.9,1)) -> panel_without_graph
panel_without_graph
#ggsave(file.path(figure_folder_path, "panel_without_graph.png")  , plot = panel_without_graph, height = 14, width = 9, dpi = 200)
```

```{r}

astrocyte@compareClusterResult %>% filter(str_detect(Description, 'RA'))
```


```{r fig.height=15, fig.width=17, message=FALSE, warning=FALSE, paged.print=FALSE}
rbind(neuron_modules,astrocyte_modules)-> hubs
hubs %>% dplyr::filter(Module == "Hyper") -> hyperhubs
hubs %>% dplyr::filter(Module == "Optimal")-> optimalhubs
hubs %>% dplyr::filter(Module == "Central")-> centralhubs
```

```{r fig.height=2, fig.width=6, message=FALSE, warning=FALSE}

my_comparisons <- list(c('Astrocyte', 'Neuron'),c("Astrocyte", "Intercellular"), c("Neuron", "Intercellular"))

centralhubs %>% get_quads(file.path(figure_folder_path, "heatmap_matrix.rds")) %>% mutate(Comparison = str_replace(Comparison, "Neuronal.*","Neuron"))   %>%
  mutate(Comparison = str_replace(Comparison, "Neuronal_cluster","Neuron")) %>%
  mutate(Comparison = str_replace(Comparison, "Astrocytic_cluster","Astrocyte")) %>%
  mutate(Comparison = str_replace(Comparison, "Neuron_vs_Astro","Intercellular"))%>%
  
ggplot(aes(x=Comparison, y=`Nodes correlations`, fill=Comparison)) + 
  geom_violin(trim=F, colour = "azure3")+  
  geom_jitter(width=0.15, alpha=0.17, size =0.21, stroke = .13, colour="black")+
  stat_compare_means( vjust= -1., hjust= 0, comparisons = my_comparisons, method = "wilcox.test", p.adjust.method = "bonferroni", label = "p.signif")+
  scale_fill_manual(values = alpha(c("chartreuse3", "chartreuse3", "chartreuse3"), .8)) + 
   theme(plot.title = element_text(hjust = 0.5),legend.position="none", axis.title.y = element_blank(), axis.text.y = element_text(angle = 0, hjust = 1), axis.title.x = element_blank())  + coord_flip()+ ggtitle("Central-hubs") + 
  scale_y_continuous(limits=c(-0.1, 1.48), breaks = c(0.0, .5 , 1)) + geom_hline(yintercept=0, linetype="dashed", color = "darkred",  size=1)-> centralhubs_corr

my_comparisons <- list(c('Astrocyte', 'Neuron'),c("Astrocyte", "Intercellular"), c("Neuron", "Intercellular"))

optimalhubs %>% get_quads(file.path(figure_folder_path, "heatmap_matrix.rds")) %>% mutate(Comparison = str_replace(Comparison, "Neuronal.*","Neuron"))   %>%
  mutate(Comparison = str_replace(Comparison, "Neuronal_cluster","Neuron")) %>%
  mutate(Comparison = str_replace(Comparison, "Astrocytic_cluster","Astrocyte")) %>%
  mutate(Comparison = str_replace(Comparison, "Neuron_vs_Astro","Intercellular"))%>%

ggplot(aes(x=Comparison, y=`Nodes correlations`, fill=Comparison)) + 
  geom_violin(trim=F, colour = "azure3")+  
  geom_jitter(width=0.15, alpha=0.12, size =0.8, stroke = .13, colour="black")+
  stat_compare_means( vjust= -1, hjust= 0, comparisons = my_comparisons, method = "wilcox.test", p.adjust.method = "bonferroni", label = "p.signif")+
  scale_fill_manual(values = alpha(c("darkorchid3", "darkorchid3", "darkorchid3"), .8)) + 
   theme(plot.title = element_text(hjust = 0.5),legend.position="none",axis.text.y = element_text(angle = 0, hjust = 1), axis.title.y = element_blank())  + coord_flip()+ ggtitle("Optimal-hubs") + 
  scale_y_continuous(limits=c(-0.1, 1.499), breaks = c(0.0, .5 , 1)) + geom_hline(yintercept=0, linetype="dashed", color = "darkred",  size=1)-> optimalhubs_corr

my_comparisons <- list(c('Astrocyte', 'Neuron'),c("Astrocyte", "Intercellular"), c("Neuron", "Intercellular"))

hyperhubs %>% get_quads(file.path(figure_folder_path, "heatmap_matrix.rds")) %>% mutate(Comparison = str_replace(Comparison, "Neuronal.*","Neuron"))   %>%
  mutate(Comparison = str_replace(Comparison, "Neuronal_cluster","Neuron")) %>%
  mutate(Comparison = str_replace(Comparison, "Astrocytic_cluster","Astrocyte")) %>%
  mutate(Comparison = str_replace(Comparison, "Neuron_vs_Astro","Intercellular"))%>%

ggplot(aes(x=Comparison, y=`Nodes correlations`, fill=Comparison)) + 
  geom_violin(trim=F, colour = "azure3")+  
  geom_jitter(width=0.2, alpha=0.25, size =1.5, stroke = .2, colour="black")+
  stat_compare_means( vjust= -1., hjust= 0, comparisons = my_comparisons, method = "wilcox.test", p.adjust.method = "bonferroni", label = "p.signif")+
  scale_fill_manual(values = alpha(c("darkorange1", "darkorange1", "darkorange1"), .8)) + 
   theme(plot.title = element_text(hjust = 0.5),legend.position="none",axis.text.y = element_text(angle = 0, hjust = 1), axis.title.y = element_blank(), axis.title.x = element_blank())  + coord_flip()+ ggtitle("Hyper-hubs") + 
  scale_y_continuous(limits=c(-0.1, 1.4899), breaks = c(0.0, .5 , 1)) + geom_hline(yintercept=0, linetype="dashed", color = "darkred",  size=1)-> hyperhubs_corr

```



```{r fig.height=15, fig.width=17, message=FALSE, warning=FALSE, paged.print=FALSE}
corr_distr_panel <- ggarrange(centralhubs_corr,hyperhubs_corr, optimalhubs_corr, ncol = 1, nrow = 3 ,  labels = c("c","d","e"))
ggarrange(NA, plot.my_counts_stacked,corr_distr_panel, widths = c(.8,.21,.5),
            labels = c("a","b",""),
            ncol = 3, nrow = 1) -> modules_panel
  
#ggarrange(modules_panel, dots_panel, nrow = 2, ncol = 1) -> panel_without_graph
#ggsave(file.path(figure_folder_path, "panel_without_graph.png")  , plot = panel_without_graph, height = 15, width = 17, dpi = 200)
```


```{r}
hubs$ID[hubs$ID %>% str_detect('_')]

write_csv(hubs, file.path(figure_folder_path, "hubs_info.csv")  )
```

















