---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(arrow)
library(magrittr)
root_path = str_extract(getwd(), '.*(?=fig)')
file.path(root_path,'aa_functions.R') -> source_path
source(source_path)


energy_subsystems <- read_delim(file.path(root_path, 'data/energy_subsystems.txt'), delim = "\n", col_names = 'energy_subsystems') %>% 
  mutate(energy_subsystems = str_replace_all(energy_subsystems, '_|-|,', ''))

centralities_vari_x_sub_x_agg <- read_parquet(file.path(root_path, 'data/final_aggregation.parquet.gzip'))
centralities_vari_x_sub_x_agg %<>% mutate(removed_rxn = str_replace_all(removed_rxn, '_|-|,', '')) 
selected_subsystems           <-  c("Glycolysis_astrocyte", "Glycolysis_neuron", "ETC_neuron", "ETC_astrocyte")
centralities_vari_x_sub_x_agg %>% filter(subsystem %in% selected_subsystems ) -> df

rxn_data                      <- read_parquet(file.path(root_path, 'data/FBA_step01_FBA_solution.parquet.gzip')) %>% 
                                 dplyr::select(c('stoichiometry','__index_level_0__' )) %>%
                                 purrr::set_names(c("reaction","ID")) %>% mutate(ID = str_replace_all(ID, '_|-|,', '')) 
get_subsystem_centralities    <- function(a_subsystem){
                                          df %>% filter(subsystem == a_subsystem) %>% dplyr::select_if(is.numeric) -> df2_numeric
                                          df %>% filter(subsystem == a_subsystem) %>% dplyr::select_if(is.character) -> df2_non_numeric
                                          #
                                          names(df2_numeric) <- paste(a_subsystem, colnames(df2_numeric), sep = '_')
                                          
                                          return(df2_numeric  )}

df %>%  filter(subsystem == selected_subsystems[1] )%>% dplyr::select_if(is.character)                                           -> df_non_numeric
cbind(df_non_numeric, map_dfc(selected_subsystems, get_subsystem_centralities)) -> wide_dataset


dataset <- wide_dataset  #%>% drop_na #%>%group_by(variation, subsystem, aggregation) %>% arrange(variation, subsystem, aggregation)
dataset %<>% dplyr::filter(!removed_rxn %in% energy_subsystems[[1]]) %>% dplyr::select(-c('subsystem'))

log2Ratio_nanmean_numpy <- dataset    %>% filter(variation == 'log2Ratio' & aggregation == 'nanmean_numpy')  %>%
                                          column_to_rownames('removed_rxn') %>% # select_if(is.numeric) %>% 
                                          dplyr::select(-c(contains("degree_centrality"),contains('xx'),contains('betweenness'),contains('load')))%>% 
                                          rownames_to_column('ID') %>%  filter(!str_detect(ID,'(^DM)|sink|\\(e\\)')) 


log2Ratio_nanmean_numpy_cells <- inner_join(log2Ratio_nanmean_numpy, rxn_data) %>% mutate(cell = if_else(str_detect(reaction, '\\[.A\\]'), 'Astrocyte', 'Neuron'))

Astrocyte <- log2Ratio_nanmean_numpy_cells %>% filter(cell == "Astrocyte") %>% column_to_rownames("ID") %>% select_if(is.numeric)
Neuron <- log2Ratio_nanmean_numpy_cells %>% filter(cell == "Neuron") %>% column_to_rownames("ID") %>% select_if(is.numeric)
```


```{r fig.height=4, fig.width=4, message=FALSE, warning=FALSE}
plot_subsystems <- function(a_subsystem, cutoff, ylims){
                            Astrocyte  %<>% dplyr::select(contains(a_subsystem))
                            Neuron     %<>% dplyr::select(contains(a_subsystem))
                            Astrocyte_flatten  <- Astrocyte %>% reduce(c) %>% .[abs(.)> cutoff]
                            Neuron_flatten     <- Neuron  %>% reduce(c) %>% .[abs(.)> cutoff]
                            centrality_flatten <- rbind(data.frame(value = Astrocyte_flatten, cell = 'Astrocyte'  ),data.frame(value = Neuron_flatten, cell = 'Neuron'  ))
                            centrality_flatten %>% ggplot(aes(x=cell, y=value, fill=cell)) +
                                geom_violin(trim=F, colour = "azure4")+
                                scale_fill_manual(values = alpha(c("royalblue3" ,"brown3"), .8))+ stat_compare_means(method = "wilcox.test",vjust= -5, hjust= 1,label = "p.signif")+ 
                                theme( plot.title = element_text(color="black", size=8, face="bold.italic"), legend.position="none",  axis.title.x=element_blank(),axis.title.y=element_blank(),
                                      axis.text.y = element_text(angle = 45, hjust = 1), axis.text.x = element_text(angle = 50, hjust = 1, size = 6)) +
                              ylim(ylims)+ geom_boxplot(width=0.12, fill="white",  outlier.size = .5) +
                               ggtitle(str_replace(a_subsystem, '\\_',' ' )) +
                             geom_hline(yintercept=0, linetype="dashed", color = "black",  size=.3) +
                              coord_flip() -> gg_violin_box
                            return(gg_violin_box)
}

cutoff_fold_change <- 0.002
plot_subsystems('ETC_astrocyte', cutoff_fold_change,  c(-0.05, 0.05)) -> ETC_astrocyte
plot_subsystems('Glycolysis_astrocyte', cutoff_fold_change,  c(-0.04, 0.055)) -> Glycolysis_astrocyte
plot_subsystems('ETC_neuron', cutoff_fold_change,  c(-0.07, 0.07)) -> ETC_neuron
plot_subsystems('Glycolysis_neuron', cutoff_fold_change,  c(-0.05, 0.05)) -> Glycolysis_neuron

ggarrange(Glycolysis_neuron, ETC_neuron, Glycolysis_astrocyte, ETC_astrocyte, nrow = 2, ncol = 2, labels = c("a", "b","c","d")) %>%
annotate_figure(                bottom = text_grob("Nodal contribution (fold change)", 
                                  hjust = 1.3, x = 1, face = "bold", size = 10), fig.lab.face = "bold") -> left_vertical_panel
left_vertical_panel
```


```{r fig.height=2, fig.width=6, message=FALSE, warning=FALSE}
Astrocyte['cell'] = "Astrocyte"
Neuron['cell']    = "Neuron"
rbind(Astrocyte, Neuron) -> both_cells_with_cells

#library(naniar)
#both_cells_with_cells_numeric <- both_cells_with_cells %>% select_if(is.numeric)
#both_cells_with_cells_numeric %<>%  replace_with_na_all(condition =  ~.x >= cutoff_fold_change)
  
```


```{r fig.height=5, fig.width=6, message=FALSE, warning=FALSE}
library(scales)
library(WGCNA)
std_rescale <- function(x) { asinh(abs(x)/2)/log(10) %>% rescale(to = c(0,1))  }
my.corr.mat         <- both_cells_with_cells %>% select_if(is.numeric)  %>%transposeBigData %>% scale   %>% cor(method = "kendall" ) 

#my.corr.mat         <-both_cells_with_cells_numeric %>%transposeBigData %>% scale   %>% cor(method = "kendall", use=  "complete.obs") 


absolute_centrality <- both_cells_with_cells %>% select_if(is.numeric)  %>%  mutate(absCent = sqrt(rowSums(( (abs(across()))  )^2 ))) %>% .[['absCent']]%>% rescale(to = c(0,1)) 



both_cells_with_cells['AbsoluteC'] <- absolute_centrality  %>%std_rescale

left_annotation <- rowAnnotation(`Nodes` = both_cells_with_cells[['cell']], annotation_name_gp= gpar(fontsize = 8),
                                 col = list( `Nodes` = c(
                "Astrocyte"        = "royalblue2", 
                 "Neuron"           = "brown3" )))
  
 right_annotation <-rowAnnotation(gap = unit(12, "points"),annotation_name_gp= gpar(fontsize = 8),
                                  AC = anno_barplot(bar_width = 0.001,width = unit(.7, "cm"), border = T,absolute_centrality, gp = gpar(col = 'seagreen4')))

 
both_cells_with_cells %>% select_if(is.numeric)  %>% scale  %>%transposeBigData %>% scale %>% t -> scaled_centralities

?hclust
library(circlize)
 col_fun = colorRamp2(c(-1, 0, 1), c("purple4", "white", "orangered3"))

ht <- Heatmap(my.corr.mat,col = col_fun, name = "Correlation",  
                left_annotation =left_annotation,
                right_annotation=right_annotation,
                clustering_distance_columns  = function(m)   dist(m, method = 'euclidean'),
                cluster_columns              = function(x) fastcluster::hclust(dist(x), "centroid"),
                
                clustering_distance_rows   = function(m)   dist(m, method = 'euclidean'),
                cluster_rows               = function(x) fastcluster::hclust(dist(x), "centroid"),
               # row_km = 2,
              #  column_km = 2,
                border = TRUE,
                row_dend_width    = unit(.5, "cm"),
                column_dend_height = unit(.5,"cm"),
                row_gap = unit(2, "mm"),
                column_gap = unit(2, "mm"),
                width = unit(5, "cm"), 
                height = unit(5, "cm"),
               # column_title = c( "Neuronal cluster" , "Astrocytic cluster"),
                column_title_gp = gpar(fontsize = 7),
                column_names_gp = gpar(fontsize = 7),
                row_title_rot  = 0,
                show_column_names    = F,
                show_row_names    = F,
                row_names_gp = gpar(fontsize = 7),
                #row_title = c("Neuronal\n cluster", "Astrocytic\n cluster"),
                row_title_gp = gpar(fontsize = 7))

for_cutoff <- inner_join(both_cells_with_cells %>% rownames_to_column("ID") , dplyr::select(log2Ratio_nanmean_numpy_cells, c(ID, cell)) )

```
```{r fig.height=2, fig.width=6, message=FALSE, warning=FALSE}
####################
Astrocyte_Absolute_Centrality <-  dplyr::filter(for_cutoff, cell == "Astrocyte")[c("ID","cell","AbsoluteC")]
Neuron_Absolute_Centrality <-  dplyr::filter(for_cutoff, cell == "Neuron")[c("ID","cell","AbsoluteC")]



write_csv(Astrocyte_Absolute_Centrality, file.path(root_path, 'data/Astrocyte_Absolute_Centrality.csv'))
write_csv(Neuron_Absolute_Centrality, file.path(root_path, 'data/Neuron_Absolute_Centrality.csv'))
```

```{r fig.height=2, fig.width=6, message=FALSE, warning=FALSE}
get_quantiles_cutoff_plot<- function(df, a_seed = 23, x_just = .69, y_just = 3, palette = 1){
                set.seed(a_seed)
                df2 <- tibble(cluster = df[["mean_shift_clusters"]],VectorNorm = df[["AbsoluteC"]]) 
                df2 %>%    group_by(cluster) %>%   mutate( min = min(VectorNorm)) %>% arrange(min) %>% .[["min"]] %>% max  -> cutoff
                VectorNorm <- df2$VectorNorm
              dens <- density(VectorNorm)
              df <- data.frame(x=dens$x, y=dens$y)
              probs <- c(.5, .90)
              quantiles <-quantile(VectorNorm, prob=probs)
              df$quant <- factor(findInterval(df$x,quantiles))
              #
              ggplot(df, aes(x,y)) + geom_line() + geom_ribbon(aes(ymin=0, ymax=y, fill=quant)) + 
              scale_x_continuous(breaks=quantiles) + 
              scale_fill_brewer(guide="none", palette = palette)+
              geom_vline(xintercept=quantiles[[2]], linetype="dashed", color = "red3",  size=.5) + ylab(NULL) + 
              xlab("Quantile")+ annotate("text", x = x_just, y = y_just, label = "Mean-shift boundary", size =3,  color = "red4") +
                theme(axis.title.x =element_blank(), axis.title.y = element_blank())-> quantiles_cutoff
              
              return(list(quantiles_cutoff,quantiles[[2]], cutoff))}
#####################
Astrocyte_Absolute_Centrality_clusterized <- read_csv(file.path(root_path,"data/Astrocyte_Absolute_Centrality_clusterized.csv"))
Neuron_Absolute_Centrality_clusterized    <- read_csv(file.path(root_path,"data/Neuron_Absolute_Centrality_clusterized.csv"))

Neuron_quantiles_bondary    <-  get_quantiles_cutoff_plot(Neuron_Absolute_Centrality_clusterized, x_just = .69,y_just = 2.5, palette = "YlOrBr")[[1]]  #7
Astrocyte_quantiles_bondary <-  get_quantiles_cutoff_plot(Astrocyte_Absolute_Centrality_clusterized, x_just = 1.013,y_just = 2,  palette = "Blues")[[1]]


ggarrange(Neuron_quantiles_bondary, Astrocyte_quantiles_bondary, nrow = 2, ncol = 1, common.legend = F) %>%



annotate_figure(bottom = text_grob("Quantils",        hjust =  6, vjust = 0 , x = 1, face = "bold", size = 10), 
                left = text_grob("Absolute Centrality",hjust = 0.3,vjust = -0.4, x = 1, face = "bold", size = 9, rot = 90), 
                fig.lab.face = "bold")  ->  gg_Quantiles_bondaries

gg_Quantiles_bondaries
```

```{r fig.height=2, fig.width=6, message=FALSE, warning=FALSE}
get_quantiles_cutoff_plot(Neuron_Absolute_Centrality_clusterized)-> Neuron_cutoff
get_quantiles_cutoff_plot(Astrocyte_Absolute_Centrality_clusterized) ->Astrocyte_cutoff 

#dplyr::filter(for_cutoff, cell == "Astrocyte")[["AbsoluteC"]] %>% get_quantiles_cutoff_plot(a_seed = 7) -> Astrocyte_cutoff
#dplyr::filter(for_cutoff, cell == "Neuron")[["AbsoluteC"]] %>% get_quantiles_cutoff_plot(a_seed = 1111)    -> Neuron_cutoff
dplyr::filter(for_cutoff, cell == "Astrocyte") %>% filter(AbsoluteC > Astrocyte_cutoff[[3]]) ->  Astrocyte_filtered
dplyr::filter(for_cutoff, cell == "Neuron") %>% filter(AbsoluteC > Neuron_cutoff[[3]])       ->  Neuron_filtered


#for_cutoff[["AbsoluteC"]]%>% get_quantiles_cutoff_plot(a_seed = 0) -> whole_cutoff;whole_cutoff[[1]]
#for_cutoff %>% filter(AbsoluteC > whole_cutoff[[2]])    -> both_cells_with_cells
rbind(Astrocyte_filtered, Neuron_filtered) -> both_cells_with_cells

filtered_centralities_cells <- both_cells_with_cells %>% dplyr::select(c(ID, cell, AbsoluteC)) %>% purrr::set_names(c("ID","Node type","value")) %>% dplyr::filter(!ID %in% energy_subsystems[[1]])

gene_rxns_whole_NAMU      <- read_csv(file.path(root_path,'data/gene_rxns_whole_NAMU.csv' ))

entrez_Neuron <-  gene_rxns_whole_NAMU %>% filter(ID %in% filtered_centralities_cells[["ID"]]) %>% filter(cell == "Neuron")   %>% .[["gene"]] %>% na.omit()%>% unique
entrez_Astrocyte <- gene_rxns_whole_NAMU %>% filter(ID %in% filtered_centralities_cells[["ID"]]) %>% filter(cell == "Astrocyte")%>% .[["gene"]] %>% na.omit()%>%unique
all_central_genes <- list(Neuron = entrez_Neuron, Astrocyte = entrez_Astrocyte)

c(
length(all_central_genes[["Neuron"]]),
length(all_central_genes[["Astrocyte"]]),
length(unique(c(all_central_genes[["Neuron"]], all_central_genes[["Astrocyte"]]))))



write(all_central_genes[["Neuron"]], file.path(root_path,'data/genes_entrez_central_neuron.txt' ))
write(all_central_genes[["Astrocyte"]], file.path(root_path,'data/genes_entrez_central_astrocyte.txt' ))
```







```{r fig.height=8, fig.width=3}

filtered_centralities_cells %>% ggplot(aes(x= reorder(ID, value),  y= value, fill = `Node type`)) + 
  geom_bar(stat='identity') + facet_grid(. ~ `Node type`) +
  theme(strip.text.x = element_text(size = 8), axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=7),legend.title = element_blank(),
                                    axis.title.x=element_blank(),axis.title.y=element_blank(),legend.position="top",axis.text.y=element_text(angle=0,hjust=1,vjust=.1,size=5),
                                    axis.ticks = element_blank())+ theme(legend.key.height= unit(.25, 'cm'),
        legend.key.width= unit(.32, 'cm'), legend.title = element_blank(), legend.text = element_text(size=8)) +
                              scale_fill_brewer(palette = "Dark2") + coord_flip()-> optimality #
optimality_panel <- ggarrange(optimality, ncol = 1, nrow = 1,  labels = c('g') ) %>%  annotate_figure(left = text_grob("Reactions", rot = 90, size = 9), bottom = text_grob("Absolute Centrality", rot = 0, size = 9))
optimality_panel
```


```{r fig.height=3, fig.width=5}
library(clusterProfiler)
library(ReactomePA)
kk <- compareCluster(all_central_genes, fun="enrichKEGG", pvalueCutoff=1e-2, pAdjustMethod="holm", 
                 qvalueCutoff=1e-2, minGSSize=5, maxGSSize = 30)


dotplot(kk, font.size = 6.5, title = NULL, label_format =55, showCategory = 10, shape = F)+  theme(legend.key.height= unit(.15, 'cm'),
        legend.key.width= unit(.32, 'cm'), legend.title = element_text(size=7), legend.text = element_text(size=5)) +
     guides(size = guide_legend(order = 2, 
         keyheight = unit(0, 'inch'))) -> dotplot_kk
```
```{r fig.height=3, fig.width=5}
pp <- compareCluster(all_central_genes, fun="ReactomePA::enrichPathway", pvalueCutoff=1e-2, pAdjustMethod="holm", 
                 qvalueCutoff=1e-2, minGSSize=5, maxGSSize = 15)

dotplot(pp, font.size = 7, title = NULL, label_format =50, showCategory = 10, shape = F)  +  theme(legend.key.height= unit(.15, 'cm'),
        legend.key.width= unit(.32, 'cm'), legend.title = element_text(size=7), legend.text = element_text(size=5)) +
     guides(size = guide_legend(order = 2, 
         keyheight = unit(0, 'inch')))-> dotplot_pp
```







```{r fig.height=5.5, fig.width=4}
library(ggplotify)

left_vertical_panel_heatmap<- ggarrange(left_vertical_panel, as.ggplot(ht), nrow = 2, ncol = 1, heights = c(1,1), labels = c("","e")) 
```

```{r fig.height=4, fig.width=7, warning=FALSE}

library(PCAtools)
get_pca <- function(my.corr.mat, total.abs.centrality, node_types){

p <- pca(my.corr.mat)

cbind(p$rotated$PC1, p$rotated$PC2) %>% as.matrix %>% as.data.frame-> my_pca
my_pca %>%  cbind(node_types) %>% set_colnames(c('PC1','PC2','Nodes')) -> to.pca.scatter
total.abs.centrality -> AC
b <- ggplot(to.pca.scatter, aes(x = PC1, y = PC2)) 
b +   scale_color_manual(labels = c("Astrocyte",'Neuron'), values =  c("royalblue2",'brown3')) +
  theme(legend.key.height= unit(.2, 'cm'), legend.title = element_text(size=7), legend.position="right", legend.box = "vertinal")+ geom_point( aes(size=AC, color= Nodes), alpha = 0.2,stroke = 1.2)-> pca_node_centrality

list(pca_node_centrality, p)
}
my.corr.mat         <- both_cells_with_cells %>% select_if(is.numeric)  %>%transposeBigData %>% scale   %>% cor(method = "kendall" ) 
absolute_centrality <- both_cells_with_cells %>% select_if(is.numeric)  %>%  mutate(absCent = rowSums(abs(across()))) %>% .[['absCent']] %>% rescale(c(0,1))
node_types          <-  both_cells_with_cells[['cell']]
PCA                 <-get_pca(my.corr.mat, absolute_centrality, node_types)

```





```{r fig.height=7, fig.width=4}
library(ggplotify)

heatmap_cutoff <-ggarrange(left_vertical_panel_heatmap, quantiles_cutoff, ncol = 1, nrow = 2, labels = c("", "f"), heights = c(1,.2), vjust = -1)

```






```{r fig.height=7, fig.width=6}



ggarrange(heatmap_cutoff, optimality_panel, ncol = 2, nrow = 1, widths = c(1.8,1))
```









```{r}

```


