---
title: "Figure 2: Pairwise correlations between nodal contributions and consensus criteria to determine topological hubs, A-c subplots"
output: html_notebook
author: "Alejandro Javier Acevedo Aracena, PhD - a.acevedo.aracena@gmail.com"
date: "May 22th, 2021"
---
Set paths
```{r message=FALSE, warning=FALSE}
figure <- 'Figure_2'
local_working_directory <- "~/AA_PostDoc/Acevedo_et_al_2021_neuron_astrocyte_metabolism"
file.path(local_working_directory,figure)      -> figure_folder_path
file.path(local_working_directory,'aa_functions.R') -> source_path
```


```{r message=FALSE, warning=FALSE}
source(source_path)
all_data          <-readr::read_rds(file.path(local_working_directory,'Data/all_data.rds'))
only_centralities <- readr::read_rds(file.path(local_working_directory,'Data/only_centralities.rds'))
```


```{r message=FALSE, warning=FALSE}
get_total_centralities(only_centralities)-> total.abs.centrality
get_correlation_matrices(only_centralities)-> my.corr.matrix
get_node_types(all_data) -> node_types
get_node_IDs(all_data) -> node_ids
rownames(my.corr.matrix) <- node_ids
colnames(my.corr.matrix) <- node_ids
generate_heatmap(my.corr.matrix, total.abs.centrality, node_types) -> ht
my_heatmap = grid.grabExpr(draw(ht))
get_heatmap_data(ht,node_types, all_data) -> heatmap_data
my_comparisons <- list( c("Neuronal_cluster", "Astrocytic_cluster"), 
                        c("Neuronal_cluster", "Neuron_vs_Astrocyte"), 
                        c("Astrocytic_cluster", "Neuron_vs_Astrocyte") )
plot_quads_corrs( heatmap_data$quads, my_comparisons) -> corr_comparisons
get_pca(my.corr.matrix, total.abs.centrality, node_types) -> pca_node_centrality
```

##### compare neural versus astrocytic absolute vitality       
```{r}
cbind(total.abs.centrality,node_types) %>% as.data.frame %>% 
  mutate(cell = if_else(str_detect(node_types, '(A|a)stro'), "Astrocyte", "Neuron")) %>% 
  select(c(total.abs.centrality,cell)) %>% purrr::set_names("AV","cell") -> hola
library(magrittr)
hola$AV %<>% as.numeric()

library(ggplot2)
# Basic stripchart
compare <-list()
compare[[1]] <- c("Astrocyte", "Neuron")

ggplot(hola, aes(x=cell, y=AV, fill=cell)) + 
  geom_violin(trim=F, color="azure4") + geom_boxplot(width=0.02, fill="white") + theme(legend.position="none")+ 
 scale_fill_manual(values=c("cyan4", "brown3")) + stat_compare_means( vjust= -1., hjust= 1.2)


```


```{r message=FALSE, warning=FALSE,  fig.height=8, fig.width=9}
upper_panel <- ggarrange(my_heatmap  , ncol = 1, widths = c(1),  labels = c('a'))
bottom_panel <- ggarrange( corr_comparisons,pca_node_centrality , NA, ncol = 3, widths  = c(.16,.55,.33) , labels = c('b','c',"d"),
                                                 hjust = 0, vjust = 1)
panel_without_graph <-  ggarrange(upper_panel, bottom_panel, nrow = 2, heights = c(.6,.4))
panel_without_graph
```


```{r message=FALSE, warning=FALSE,  fig.height=8, fig.width=9}
ggsave(file=file.path(figure_folder_path, "panel_without_graph.png"), plot=panel_without_graph, width=9, height=8, dpi = 500)
```

```{r}
data.frame(ID =node_ids,total_centrality = total.abs.centrality ) -> total_centrality_by_node
write_csv(total_centrality_by_node, file.path(figure_folder_path, "total_centrality_by_node.csv"))
file.path(local_working_directory, "Figure_4") -> path_to_fig4
 heatmap_data$ht_Neuronal_cluster%>%  write_rds(file.path(path_to_fig4, "ht_Neuronal_cluster.rds"))
 heatmap_data$ht_Astrocytic_cluster%>%  write_rds(file.path(path_to_fig4, "ht_Astrocytic_cluster.rds"))
 heatmap_data$ht_Neuron_vs_Astrocyte%>%  write_rds(file.path(path_to_fig4, "ht_Neuron_vs_Astrocyte.rds"))
 heatmap_data$heatmap_matrix%>%  write_rds(file.path(path_to_fig4, "heatmap_matrix.rds"))
```








