---
title: "R Notebook"
output: html_notebook
---


```{r}
library(arrow)
library(tidyverse)
library(magrittr)
library(tidyverse)
library(magrittr)
library(clusterProfiler)
library(ReactomePA)
library(stringi)
```


```{r}
root_path <- '/home/alejandro/AA_PostDoc/Acevedo_et_al_2021_neuron_astrocyte_metabolism/NAMU2021b'

centralities_vari_x_sub_x_agg <- read_parquet(file.path(root_path, 'data/final_aggregation.parquet.gzip'))
centralities_vari_x_sub_x_agg %<>% mutate(removed_rxn = str_replace_all(removed_rxn, '_|-|,', '')) 

dataset <- centralities_vari_x_sub_x_agg %>% filter(subsystem == 'FBA_sensitive')  %>% drop_na %>% mutate(absCent = rowSums(across(matches('centrality|pagerank')))) %>% 
                     group_by(variation, subsystem, aggregation) %>% arrange(variation, subsystem, aggregation, desc(absCent)) 


NormalizedDelta_quadratic_mean <- dataset    %>% filter(variation == 'NormalizedDelta' & aggregation == 'quadratic_mean') %>% select(-c(absCent, degree_centrality)) %>% 
                                  column_to_rownames('removed_rxn') %>% select_if(is.numeric)
NormalizedDelta_nanmean_numpy <- dataset    %>% filter(variation == 'NormalizedDelta' & aggregation == 'nanmean_numpy')  %>% select(-c(absCent, degree_centrality)) %>% 
                                  column_to_rownames('removed_rxn') %>% select_if(is.numeric)


log2Ratio_nanmean_numpy <- dataset    %>% filter(variation == 'log2Ratio' & aggregation == 'nanmean_numpy')  %>% select(-c(absCent, degree_centrality)) %>% 
                                  column_to_rownames('removed_rxn') %>% select_if(is.numeric)


log2Ratio_quadratic_mean <- dataset    %>% filter(variation == 'log2Ratio' & aggregation == 'quadratic_mean')  %>% select(-c(absCent, degree_centrality)) %>% 
                                  column_to_rownames('removed_rxn') %>% select_if(is.numeric)
```


```{r}

Astrocyte_IDs_centrality_optimality <- read_csv(file.path(root_path, 'data/Astrocyte_IDs_centrality_optimality.csv')) %>% select(-c(matches('Centrality|Optimality'))) %>% 
                                        unite("genes", recon3_genes:KEGG_genes, remove = T, sep = ',', na.rm = T)
Neuron_IDs_centrality_optimality <- read_csv(file.path(root_path, 'data/Neuron_IDs_centrality_optimality.csv')) %>% 
                                           select(-c(matches('Centrality|Optimality'))) %>% unite("genes", recon3_genes:KEGG_genes, remove = T, sep = ',', na.rm = T)

Astrocyte_rxn_genes <- Astrocyte_IDs_centrality_optimality %>% select(c(ID,genes)) %>% mutate(gene = str_split(genes, ",") ) %>% unnest(gene) %>% 
                                                    mutate(gene = str_trim(gene, side = "both")) %>% select(-genes)

Neuron_rxn_genes <- Neuron_IDs_centrality_optimality %>% select(c(ID,genes)) %>% mutate(gene = str_split(genes, ",") ) %>% unnest(gene) %>% 
                          mutate(gene = str_trim(gene, side = "both")) %>% select(-genes)





reactions_that_donnot_have_gene <- log2Ratio_nanmean_numpy %>% rownames_to_column('ID') %>% mutate(cell = if_else(ID %in% Astrocyte_rxn_genes$ID, 'Astrocyte', NULL ))%>%
                                mutate(cell = if_else(ID %in% Neuron_rxn_genes$ID, 'Neuron', cell )) %>% filter(is.na(cell)) %>%  filter(!str_detect(ID,'(^DM)|sink|\\(e\\)')) %>% .[['ID']]
```


```{r}
gene_rxn <- read_csv(file.path(root_path, 'data/NAMU_genes_2_rxns_mapping.csv')) %>% set_names(c('gene','rxn')) %>% 
                             mutate(gene = str_replace_all(gene,'\\[|\\]',''), rxn = str_replace_all(rxn,'\\[|\\]',''))%>% 
                     mutate(rxn = str_split(rxn, "', '") )%>% unnest(rxn) %>% mutate(rxn = str_trim(rxn, side = "both"))%>%    
                 mutate(rxn = str_replace_all(rxn,"\\'",''))  %>% 
                filter(!str_detect(rxn,'(DM_)|sink|\\(e\\)')) %>% mutate(rxn = str_replace_all(rxn, '_|-|,', '')) 


neuron_astro_genes_q_faltan <- gene_rxn %>% filter(rxn %in% reactions_that_donnot_have_gene) %>% mutate(gene = str_replace_all(gene,"\\?",'')) 

Neuron_genes_q_faltan  <- neuron_astro_genes_q_faltan%>% filter(str_detect(rxn, 'Neuron')) %>% set_names(c('gene', "ID")) %>% select(c("ID",'gene'))


Astro_genes_q_faltan <-  neuron_astro_genes_q_faltan%>% filter(!str_detect(rxn, 'Neuron')) %>% set_names(c('gene', "ID")) %>% select(c("ID",'gene'))
```

```{r}

Astrocyte_rxn_genes <- rbind(Astrocyte_rxn_genes, Astro_genes_q_faltan) %>% mutate(cell = 'Astrocyte')
Neuron_rxn_genes <- rbind(Neuron_rxn_genes, Neuron_genes_q_faltan) %>% mutate(cell = 'Neuron')
rbind(Neuron_rxn_genes, Astrocyte_rxn_genes) %>% write_csv(file.path(root_path, 'data/gene_rxns_whole_NAMU.csv'))

log2Ratio_nanmean_numpy_cells <- log2Ratio_nanmean_numpy %>% rownames_to_column('ID') %>% mutate(cell = if_else(ID %in% Astrocyte_rxn_genes$ID, 'Astrocyte', NULL ))%>%
                                mutate(cell = if_else(ID %in% Neuron_rxn_genes$ID, 'Neuron', cell )) %>%  filter(!str_detect(ID,'(^DM_)|sink|\\(e\\)')) %>% drop_na()

```

```{r}
library(ggplot2)
library(PCAtools)
df <- log2Ratio_nanmean_numpy_cells %>% select(-c(betweenness_centrality, load_centrality))

scale(t(as.matrix(df %>% column_to_rownames('ID') %>%select(-cell)))) -> my_matrix
#cor(scale(t(as.matrix(log2Ratio_nanmean_numpy)))) -> my_corr
p <- pca(my_matrix, removeVar = 0)

cbind(
p$rotated['PC1'],
p$rotated['PC2'], log2Ratio_nanmean_numpy_cells['cell']) -> df

ggplot(df, aes(x = PC1, y = PC2, color= cell))+ geom_point()
```

```{r}

df <- log2Ratio_nanmean_numpy_cells %>% select(-c(betweenness_centrality, load_centrality))

(cor(t(scale(as.matrix(df %>% column_to_rownames('ID') %>%select(-cell)))))) -> my_corr
p <- pca(my_corr, removeVar = 0)

cbind(
p$rotated['PC1'],
p$rotated['PC2'], log2Ratio_nanmean_numpy_cells['cell']) -> df

ggplot(df, aes(x = PC1, y = PC2, color= cell))+ geom_point()
```


```{r}

df <- log2Ratio_nanmean_numpy_cells %>% select(c(betweenness_centrality, load_centrality,ID,cell))


t(scale(as.matrix(df %>% column_to_rownames('ID') %>%select(-cell)))) -> my_matrix
#cor(scale(t(as.matrix(log2Ratio_nanmean_numpy)))) -> my_corr
p <- pca(my_matrix, removeVar = 0)

cbind(
p$rotated['PC1'],
p$rotated['PC2'], log2Ratio_nanmean_numpy_cells['cell']) -> df

ggplot(df, aes(x = PC1, y = PC2, color= cell))+ geom_point()
```
```{r}

log2Ratio_nanmean_numpy_cells %>%

mutate(VectorNorm = rowSums(abs(across(matches('centrality|pagerank'))))) %>% arrange(desc(VectorNorm))->log2Ratio_nanmean_numpy_cells_VectorNorm  




log2Ratio_nanmean_numpy_cells_VectorNorm %>% .[['VectorNorm']] -> VectorNorm

```

```{r}

k <- kmeans(VectorNorm,2,nstart = 25)
tibble(cluster = k$cluster,VectorNorm) %>%  group_by(cluster) %>% arrange(cluster, desc(VectorNorm )) %>% .[[nrow(.),'VectorNorm']] -> cutoff
cutoff
```



```{r}
dens <- density(VectorNorm)
df <- data.frame(x=dens$x, y=dens$y)

probs <- c(0.703)

quantiles <-quantile(VectorNorm, prob=probs)



df$quant <- factor(findInterval(df$x,quantiles))
ggplot(df, aes(x,y)) + geom_line() + geom_ribbon(aes(ymin=0, ymax=y, fill=quant)) + scale_x_continuous(breaks=quantiles) + scale_fill_brewer(guide="none")

```


```{r}
library(stringi)

log2Ratio_nanmean_numpy_cells_VectorNorm %>% filter(VectorNorm >= cutoff) %>% filter(cell == 'Neuron')%>% .[['ID']]-> Neuron_hubs

log2Ratio_nanmean_numpy_cells_VectorNorm %>% filter(VectorNorm >= cutoff) %>% filter(cell == 'Astrocyte') %>%.[['ID']]-> Astrocyte_hubs

 
Entrez_Neuron_hubs <- Neuron_rxn_genes %>% filter(ID %in% Neuron_hubs)%>% .[['gene']]%>% unique %>% stri_remove_empty

Entrez_Astrocyte_hubs<- Astrocyte_rxn_genes %>% filter(ID %in% Astrocyte_hubs)%>% .[['gene']]%>% unique %>% stri_remove_empty




write(Entrez_Neuron_hubs, file.path(root_path, 'data/genes_entrez_central_neuron.txt'))
write(Entrez_Astrocyte_hubs, file.path(root_path, 'data/genes_entrez_central_astrocyte.txt'))
```


```{r}
kk <- enrichKEGG(entrez, organism="hsa", pvalueCutoff=1e-5, pAdjustMethod="hommel", 
                 qvalueCutoff=1e-5, minGSSize=30)
enrichKEGG_df <- kk@result %>% filter( p.adjust<1e-6 & qvalue < 1e-6 ) %>% 
dplyr::select(c(Description,GeneRatio,p.adjust, qvalue)) %>% head(10) 

rr = enrichPathway(entrez, pvalueCutoff=1e-5, pAdjustMethod="hommel", 
                 qvalueCutoff=1e-5, minGSSize=30)

enrichPathway_df <- rr@result %>% filter( p.adjust<1e-6 & qvalue < 1e-6 ) %>% 
dplyr::select(c(Description,GeneRatio,p.adjust, qvalue)) %>% head(10)


oo <- enrichGO(entrez,OrgDb = 'org.Hs.eg.db', pvalueCutoff=.0001, qvalueCutoff=.0001,
            ont = 'BP', pAdjustMethod = 'hommel', minGSSize = 30)

enrichGO_df <- oo@result%>% filter( p.adjust<1e-15 & qvalue < 1e-15 ) %>% 
             dplyr::select(c(Description,GeneRatio,p.adjust, qvalue)) %>% head(10)


```

```{r}
enrichKEGG_df

enrichPathway_df
```



