---
title: ""
output: html_notebook
author: "Alejandro Javier Acevedo Aracena, PhD - a.acevedo.aracena@gmail.com"
date: "May 23th, 2021"
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(clusterProfiler)
library(ReactomePA)
library(stringi)
```

```{r message=FALSE, warning=FALSE}

local_path_to_root <- "~/AA_PostDoc/Acevedo_et_al_2021_neuron_astrocyte_metabolism/NAMU2021b"
setwd(local_path_to_root)

Astrocyte_IDs_centrality_optimality <- read_csv(file.path(local_path_to_root, 'data/Astrocyte_IDs_centrality_optimality.csv')) %>%dplyr::select(-c(matches('Centrality|Optimality'))) %>% unite("genes", recon3_genes:KEGG_genes, remove = T, sep = ',', na.rm = T)

Neuron_IDs_centrality_optimality <- read_csv(file.path(getwd(), 'data/Neuron_IDs_centrality_optimality.csv')) %>% dplyr::select(-c(matches('Centrality|Optimality'))) %>% unite("genes", recon3_genes:KEGG_genes, remove = T, sep = ',', na.rm = T)
all_rxn_genes <- rbind(Astrocyte_IDs_centrality_optimality, Neuron_IDs_centrality_optimality)
all_rxn_genes %<>% dplyr::select(c(ID,genes)) %>% mutate(gene = str_split(genes, ",") ) %>% unnest(gene) %>% mutate(gene = str_trim(gene, side = "both"))
FBA_sensitivities <- read_csv('data/FBA_sensitivities.csv')
tail(all_rxn_genes)
all_rxn_genes
```

```{r message=FALSE, warning=FALSE}

FBA_sensitivities %<>% mutate(ID = str_replace_all(...1, '_|-|,', '')) 
sensitive_rxns<-FBA_sensitivities$ID
library(stringi)
library(magrittr)

neuron <- sensitive_rxns[sensitive_rxns %>% str_detect('.*Neuron')]
astrocyte <- sensitive_rxns[!sensitive_rxns %>% str_detect('.*Neuron')]


#file.path(local_path_to_root,  'data/entrez_astrocyte_sensitive_rxn_genes.txt') %>%  write_csv()


rbind(all_rxn_genes, Astro_genes_q_faltan, Neuron_genes_q_faltan) %>% filter(ID %in% neuron)  -> neuron_sensitive_rxns_genes
rbind(all_rxn_genes, Astro_genes_q_faltan, Neuron_genes_q_faltan) %>% filter(ID %in% astrocyte) -> astrocyte_sensitive_rxns_genes

neuron_sensitive_rxn_genes <- neuron_sensitive_rxns_genes$gene %>% str_replace_all('\\..','') %>% unique %>% stri_remove_empty
astrocyte_sensitive_rxn_genes <- astrocyte_sensitive_rxns_genes$gene %>% str_replace_all('\\..','') %>% unique %>% stri_remove_empty

write(neuron_sensitive_rxn_genes,file.path(local_path_to_root,  'data/entrez_neuron_sensitive_rxn_genes.txt') )
write(astrocyte_sensitive_rxn_genes,file.path(local_path_to_root,  'data/entrez_astrocyte_sensitive_rxn_genes.txt'))
```

```{r message=FALSE, warning=FALSE}
?enrichKEGG
kk <- enrichKEGG(entrez, organism="hsa", pvalueCutoff=1e-5, pAdjustMethod="hommel", 
                 qvalueCutoff=1e-5, minGSSize=30)

enrichKEGG_df <- kk@result %>% filter( p.adjust<1e-6 & qvalue < 1e-6 ) %>% 
dplyr::select(c(Description,GeneRatio,p.adjust, qvalue)) %>% head(10) 

rr = enrichPathway(entrez, pvalueCutoff=1e-5, pAdjustMethod="hommel", 
                 qvalueCutoff=1e-5, minGSSize=30)

enrichPathway_df <- rr@result %>% filter( p.adjust<1e-6 & qvalue < 1e-6 ) %>% 
dplyr::select(c(Description,GeneRatio,p.adjust, qvalue)) %>% head(10)


oo <- enrichGO(entrez,OrgDb = 'org.Hs.eg.db', pvalueCutoff=.0001, qvalueCutoff=.0001,
            ont = 'BP', pAdjustMethod = 'hommel', minGSSize = 30)

enrichGO_df <- oo@result%>% filter( p.adjust<1e-15 & qvalue < 1e-15 ) %>% 
             dplyr::select(c(Description,GeneRatio,p.adjust, qvalue)) %>% head(10)


```