---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(arrow)
library(magrittr)
library(ggplot2)
library(ggplot2)
library(rsvg)
library(ggpubr)
library(magick)
library(png)
library(ggplotify)



root_path = str_extract(getwd(), '.*(?=fig)')
file.path(root_path,'aa_functions.R') -> source_path
source(source_path)

phpps <- read_parquet(file.path(root_path,'data/FBA_step02_all_phpps.parquet.gzip' ))
phpps %>% select_if(is.character) %>% unique() %>% .[[1]] -> phpp_names
get_phpp <- function(phpp_name){
                      phpps %>% filter(index == phpp_name) %>%select_if(is.numeric) %>% as.matrix()-> arr
                      colnames(arr) <- NULL
                      arr %<>% purrr::reduce(c)
                      return(list(arr))
                      }


sapply(phpp_names, get_phpp) -> my_imported_files
```


```{r message=FALSE, warning=FALSE}
phpp_axes                 <- data.frame(glucose_uptake = my_imported_files[["glucose_uptake"]], oxygen_uptake = -1*my_imported_files[["oxygen_uptake"]])
  data.frame(phpp_axes, objective = my_imported_files[['objective']])  -> phpp_objective
  data.frame(phpp_axes, GLUVESSEC_Neuron= my_imported_files[['GLUVESSEC_Neuron']])  -> phpp_GLUVESSEC_Neuron
  data.frame(phpp_axes, L_LACt2r_Int= -1*my_imported_files[['L_LACt2r_Int']])  -> phpp_L_LACt2r_Int
  data.frame(phpp_axes, NaEX_Neuron= my_imported_files[['NaEX_Neuron']])  -> phpp_NaEX_Neuron
Y_o2_glc    = -1*my_imported_files[['oxygen_uptake']] /(my_imported_files[["glucose_uptake"]]) #my_imported_files[['GLCt1r_Neuron']] 
Y_ATP_glc   =  (abs(my_imported_files[['ATPS4m']])  + my_imported_files[['ATPS4m_Neuron']]  + my_imported_files[['PYK_Neuron']]+
                  my_imported_files[['PYK']] )/(my_imported_files[['glucose_uptake']] )# + my_imported_files[["GLCt1r_Neuron"]])
  
  data.frame(phpp_axes, Y_o2_glc= Y_o2_glc)  -> phpp_Y_o2_glc
  data.frame(phpp_axes, Y_ATP_glc= Y_ATP_glc)  -> phpp_Y_ATP_glc

list(phpp_objective,phpp_GLUVESSEC_Neuron,phpp_L_LACt2r_Int,phpp_NaEX_Neuron,phpp_Y_o2_glc,phpp_Y_ATP_glc) %>% 
  purrr::set_names(c('phpp_objective','phpp_GLUVESSEC_Neuron','phpp_L_LACt2r_Int','phpp_NaEX_Neuron','phpp_Y_o2_glc','phpp_Y_ATP_glc'))-> phpps
FBA_step01_neurotransmission_related_fluxes <- read_parquet(file.path(root_path,'data/FBA_step01_neurotransmission_related_fluxes.parquet.gzip' ))
rownames(FBA_step01_neurotransmission_related_fluxes)  <- FBA_step01_neurotransmission_related_fluxes[['__index_level_0__']]
get_phpp_contours <- function(df, inter_colors, breaks_lines, label_placement_fraction, nudge_y, colormap = "viridis"){
  df %>% 
    signif(digits = 10) %>% unique %>% set_names(c('x','y','z'))  -> df2
  
  x_glc = FBA_step01_neurotransmission_related_fluxes['GLCt1r',][[1]] # + FBA_step01_neurotransmission_related_fluxes['GLCt1r_Neuron',][[1]] 
  y_o2  = -1*FBA_step01_neurotransmission_related_fluxes['EX_o2(e)',][[1]]

df2 %>%ggplot(aes(x=x, y=y, z=z)) +
    #labs(inherit.aes = T, colour="Tff")+
    geom_contour_fill(inherit.aes = T,  breaks =  seq(0,max(df2['z']), inter_colors),  colour = "white", size = 0, alpha = 1) +
    geom_contour(inherit.aes = T, colour = "white",  breaks = breaks_lines, size = 1 )+
    geom_text_contour(breaks = breaks_lines , inherit.aes = T,  colour = "white" , skip = 0,nudge_x = 0,nudge_y = nudge_y,
                      label.placement = label_placement_fraction(frac = label_placement_fraction)) +
    scale_fill_continuous(type = colormap)+
    scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,-nudge_y)) +
    theme(legend.text =  element_text(angle = 60, size = 6), legend.title = element_text(size = 8) ,  legend.key.width = unit(.5, "cm"), legend.key.height=unit(2, "mm") ,  
          legend.position="bottom",        legend.box="horizontal",  axis.title.y=element_blank(), axis.title.x=element_blank()) +
    
    geom_point(aes(x=x_glc, y=y_o2), size = 3, colour = "red") +
    geom_segment(aes(x= x_glc, xend=x_glc , y= 13, yend=y_o2 ), colour="black", lwd=.5, linetype = 'dotted')+
    geom_segment(aes(x= 1, xend=x_glc , y= y_o2, yend=y_o2 ), colour="black", lwd=.5, linetype = 'dotted')
}

pluck(phpps,'phpp_NaEX_Neuron') %>% get_phpp_contours(inter_colors=.10, breaks_lines=c(350), label_placement_fraction=.3, nudge_y=2.2)  +guides(fill = guide_colorbar(title ="NaEx"))         ->phpp_NaEX_Neuron
pluck(phpps,'phpp_Y_o2_glc')  %>% get_phpp_contours(inter_colors=.04, breaks_lines=c(6.0), label_placement_fraction= 0.3 , nudge_y=2.2 ) +guides(fill = guide_colorbar(title = expression(Y['O'['2']*'/Glc']*'') ))             ->phpp_Y_o2_glc
pluck(phpps,'phpp_L_LACt2r_Int')  %>% get_phpp_contours(inter_colors=.05, breaks_lines= -1*FBA_step01_neurotransmission_related_fluxes['L-LACt2r_Int',][[1]] %>% round(3), label_placement_fraction= 0.3 , nudge_y=2.9 )+guides(fill = guide_colorbar(title ="Lact"))        ->phpp_L_LACt2r_Int
pluck(phpps,'phpp_GLUVESSEC_Neuron' ) %>% get_phpp_contours(inter_colors=.05, breaks_lines=FBA_step01_neurotransmission_related_fluxes['GLUVESSEC_Neuron',][[1]]%>% round(3), label_placement_fraction= 0.3 , nudge_y=2.9 )+guides(fill = guide_colorbar(title ="GluVe"))    ->phpp_GLUVESSEC_Neuron
pluck(phpps,'phpp_objective' ) %>% get_phpp_contours(inter_colors=.4, breaks_lines=c(139.731), label_placement_fraction= 0.2 , nudge_y=2.9 )+guides(fill = guide_colorbar(title ="Obj"))       ->phpp_objective

pluck(phpps,'phpp_Y_ATP_glc' ) %>% get_phpp_contours(inter_colors=.1, breaks_lines=c(28), label_placement_fraction= 0.6 , nudge_y=-3 ) +guides(fill = guide_colorbar(title = expression('Y'['ATP/Glc']*'')  )) +   scale_y_continuous(expand = c(0,-3)) ->phpp_Y_ATP_glc




```

```{r fig.height=8, fig.width=2.2, message=FALSE, warning=FALSE}
phpp_panel <-  ggarrange(phpp_NaEX_Neuron, phpp_L_LACt2r_Int, phpp_GLUVESSEC_Neuron, phpp_objective, ncol = 1,  
                         labels = c('d','e','f','g'), hjust = .45, vjust =  .9, font.label =list(size = 11, color = "black", face = "plain", family = NULL) ,  align = "hv")

phpp_panel %<>% annotate_figure(left = text_grob("Oxygen uptake rate (\U003BCM/s)", rot = 90, size = 11, vjust = -.0, hjust = 0), bottom = text_grob("Glucose uptake rate(\U003BCM/s)", rot = 0, size = 11))
phpp_panel
```

```{r message=FALSE, warning=FALSE}
FBA <- read_parquet(file.path(root_path,'data/FBA_step01_FBA_solution.parquet.gzip' ))#%>% dplyr::filter('__index_level_0__'=="AA2")
FBA %<>% column_to_rownames('__index_level_0__') %>% mutate(cell = if_else( str_detect(stoichiometry, regex('\\[.N\\]', ignore_case = F) ), 'Neuron','Astrocyte' )) %>% rownames_to_column('ID')
names(FBA) <- c("ID", "Flux","Sensitivity","Name","Reaction", "Node type")
FBA  %<>% dplyr::select(c("ID"   ,       "Name"   ,     "Reaction" ,   "Flux"  ,      "Sensitivity", "Node type"  ))%>% filter(ID!="AA2")
FBA %>% get_optimality_values %>% pluck("optimality_values")  -> optimality_values
optimality_values %<>% filter(value > 1e-10 )

plot_stats_comparison <- function(fba_values){
  optimality_values %>% dplyr::filter(variable == fba_values)  %>% 
ggplot(aes(x=`Node type`, y=value, fill=`Node type`)) + 
    geom_violin(trim=F, colour = "azure4")+
    scale_fill_manual(values = alpha(c("darkblue" ,"red4"), .8))+ stat_compare_means(aes(label = ..p.signif..),method = "wilcox.test",vjust= 0, hjust= -.5)+ 
    theme(plot.title = element_text(hjust = 0.5),legend.position="none",  axis.title.x=element_blank(),axis.title.y=element_blank(),
          axis.text.y = element_text(angle = 45, hjust = 1), axis.text.x = element_text(angle = 50, hjust = 1)) + geom_boxplot(width=0.2, fill="white", outlier.size = .5, outlier.color = "black")
  
}



Sensitivity_stats_comparison   <- plot_stats_comparison("Sensitivity")
Flux_stats_comparison          <- plot_stats_comparison("Flux")

bipartite_stimulated <- magick::image_read_svg(file.path(root_path,'fig_1/pruned_stimulated_w_attrs.svg' ))
bipartite_stimulated_Flux <- magick::image_read_svg(file.path(root_path,'fig_1/pruned_stimulated_w_attrs_Flux.svg' ))
bipartite_stimulated_Sensitivity<- magick::image_read_svg(file.path(root_path,'fig_1/pruned_stimulated_w_attrs_Sensitivity.svg' ))

gg_flux_comparisons <-  ggarrange(Flux_stats_comparison, as.ggplot(bipartite_stimulated_Flux), widths = c(1.2,1))
gg_Sensitivity_comparisons <-  ggarrange(Sensitivity_stats_comparison, as.ggplot(bipartite_stimulated_Sensitivity), widths = c(1.2,1))

gg_flux_comparisons %<>% 
annotate_figure(left = text_grob("Flux", color = "grey4", face = "plain",  rot = 90,size = 8, hjust = -.9), 
               fig.lab = "") 


gg_Sensitivity_comparisons %<>% 
annotate_figure(left = text_grob("Sensitivity", color = "grey4", face = "plain",rot = 90, size = 8, hjust = 0),   
               fig.lab = "") 

gg_duality    <- ggarrange(gg_flux_comparisons, gg_Sensitivity_comparisons, ncol = 1, nrow = 2, labels = c("i","j"), font.label =list(size = 11, color = "black", face = "plain", family = NULL) )
duality_panel <-  ggarrange(as.ggplot(bipartite_stimulated), gg_duality, ncol = 1, nrow = 2, heights = c(1,1.6), labels = c("h",""), vjust = 1.2, hjust = 0,  font.label =list(size = 11, color = "black", face = "plain", family = NULL) )
duality_panel
```

```{r fig.height=7, fig.width=6 }
library(scales)

std_rescale <- function(x) { asinh(abs(x)/2)/log(10) %>% rescale(to = c(0,1))  }
FBA -> FBA_copy; FBA_copy %<>%   mutate(optimality = sqrt(std_rescale(abs(Flux))^2 + std_rescale(abs(Sensitivity))^2)) %>% filter(optimality > 0) %>%
                mutate(Flux = std_rescale(Flux), Sensitivity = std_rescale(Sensitivity))  %>% dplyr::filter(optimality > 1e-14)
   

#FBA_copy %>% .[['optimality']]-> VectorNorm


Astrocyte_Absolute_Optimality <- FBA_copy[c("ID", "Node type","optimality")] %>% purrr::set_names(c("ID", "cell", "AbsoluteOP")) %>%  dplyr::filter(cell == "Astrocyte")
Neuron_Absolute_Optimality<- FBA_copy[c("ID", "Node type","optimality")] %>% purrr::set_names(c("ID", "cell", "AbsoluteOP")) %>%  dplyr::filter(cell == "Neuron")

write_csv(Astrocyte_Absolute_Optimality, file.path(root_path, 'data/Astrocyte_Absolute_Optimality.csv'))
write_csv(Neuron_Absolute_Optimality, file.path(root_path, 'data/Neuron_Absolute_Optimality.csv'))
```

```{r fig.height=2, fig.width=6, message=FALSE, warning=FALSE}
get_quantiles_cutoff_plot<- function(df, a_seed = 23, x_just = .69, y_just = 3, palette = 1){
                set.seed(a_seed)
                df2 <- tibble(cluster = df[["mean_shift_clusters"]],VectorNorm = df[["AbsoluteOP"]]) 
                df2 %>%    group_by(cluster) %>%   mutate( min = min(VectorNorm)) %>% arrange(min) %>% .[["min"]] %>% max  -> cutoff
                VectorNorm <- df2$VectorNorm
              dens <- density(VectorNorm)
              df <- data.frame(x=dens$x, y=dens$y)
              probs <- c(.1, .90)
              quantiles <-quantile(VectorNorm, prob=probs)
              df$quant <- factor(findInterval(df$x,quantiles))
              #
              ggplot(df, aes(x,y)) + geom_line() + geom_ribbon(aes(ymin=0, ymax=y, fill=quant)) + 
              scale_x_continuous(breaks=quantiles) + 
              scale_fill_brewer(guide="none", palette = palette)+
                
              geom_vline(xintercept=quantiles[[2]], linetype="dashed", color = "red3",  size=.5) + ylab(NULL) + 
                
              xlab("Quantile")+ annotate("text", x = x_just, y = y_just, label = "", size =1,  color = "red4") +
                theme(axis.title.x =element_blank(), axis.title.y = element_blank())-> quantiles_cutoff
              
              return(list(quantiles_cutoff,quantiles[[2]], cutoff))}
#####################
Astrocyte_Absolute_Optimality_clusterized <- read_csv(file.path(root_path,"data/Astrocyte_Absolute_Optimality_clusterized.csv"))
Neuron_Absolute_Optimality_clusterized    <- read_csv(file.path(root_path,"data/Neuron_Absolute_Optimality_clusterized.csv"))


Neuron_quantiles_cutoff_plot <-  get_quantiles_cutoff_plot(Neuron_Absolute_Optimality_clusterized, x_just = 9,y_just = .14, palette = "YlOrBr")
Astrocyte_quantiles_cutoff_plot <-  get_quantiles_cutoff_plot(Astrocyte_Absolute_Optimality_clusterized, x_just = 8,y_just = .14,  palette = "Blues")

Neuron_quantiles_bondary    <-  Neuron_quantiles_cutoff_plot[[1]]  #7
Astrocyte_quantiles_bondary <-  Astrocyte_quantiles_cutoff_plot[[1]]

#Neuron_cutoff    <- Neuron_quantiles_cutoff_plot[[3]]
#Astrocyte_cutoff <- Astrocyte_quantiles_cutoff_plot[[3]]
```


```{r fig.height=8, fig.width=2, message=FALSE, warning=FALSE}
ggarrange(Neuron_quantiles_bondary, Astrocyte_quantiles_bondary, nrow = 2, ncol = 1, common.legend = F) %>%



annotate_figure(bottom = text_grob("Quantils",        hjust =  2, vjust = 0 , x = 1, face = "plain", size = 10), 
                left = text_grob("Absolute Optimality",hjust = 0.3,vjust = -0.4, x = 1, face = "plain", size = 9, rot = 90), 
                fig.lab.face = "")  ->  gg_Quantiles_bondaries


ggarrange(duality_panel, gg_Quantiles_bondaries, nrow = 2, ncol = 1, common.legend = F, heights = c(1,.3) , labels = c("", "k"), vjust = -.2,  hjust = 0,  font.label =list(size = 11, color = "black", face = "plain", family = NULL) ) -> duality_cutoffs_panel

duality_cutoffs_panel

```


```{r fig.height=8, fig.width=4, message=FALSE, warning=FALSE}


ggarrange(phpp_panel, duality_cutoffs_panel, ncol = 2, nrow = 1, widths = c(1,1.35)) -> two_left_cols_panel
two_left_cols_panel

```

```{r}
get_quantiles_cutoff_plot(Neuron_Absolute_Optimality_clusterized)-> Neuron_cutoff
get_quantiles_cutoff_plot(Astrocyte_Absolute_Optimality_clusterized) ->Astrocyte_cutoff 


dplyr::filter(FBA_copy, `Node type` == "Astrocyte") %>% filter(optimality > Astrocyte_cutoff[[3]]) ->  Astrocyte_filtered
dplyr::filter(FBA_copy, `Node type`== "Neuron") %>% filter(optimality > Neuron_cutoff[[3]])       ->  Neuron_filtered

rbind(Astrocyte_filtered, Neuron_filtered) -> both_cells_with_cells

energy_subsystems <- read_delim(file.path(root_path, 'data/energy_subsystems.txt'), delim = "\n", col_names = 'energy_subsystems') %>% 
  mutate(energy_subsystems = str_replace_all(energy_subsystems, '_|-|,', ''))

filtered_centralities_cells <- both_cells_with_cells %>% mutate(ID = str_replace_all(ID, '_|-|,', ''))%>% dplyr::select(c(ID, `Node type`, optimality)) %>% purrr::set_names(c("ID","Node type","value")) %>% dplyr::filter(!ID %in% energy_subsystems[[1]])

```


```{r}
gene_rxns_whole_NAMU      <- read_csv(file.path(root_path,'data/gene_rxns_whole_NAMU.csv' ))

entrez_Neuron <-  gene_rxns_whole_NAMU %>% filter(ID %in% filtered_centralities_cells[["ID"]]) %>% filter(cell == "Neuron")   %>% .[["gene"]] %>% na.omit()%>% unique
entrez_Astrocyte <- gene_rxns_whole_NAMU %>% filter(ID %in% filtered_centralities_cells[["ID"]]) %>% filter(cell == "Astrocyte")%>% .[["gene"]] %>% na.omit()%>%unique
all_optimal_genes <- list(Neuron = entrez_Neuron, Astrocyte = entrez_Astrocyte)

write(all_optimal_genes[["Neuron"]], file.path(root_path,'data/genes_entrez_optimal_neuron.txt' ))
write(all_optimal_genes[["Astrocyte"]], file.path(root_path,'data/genes_entrez_optimal_astrocyte.txt' ))
```








```{r fig.height=7, fig.width=5.5 }
#ggarrange( phpp_panel, graphs_panel, ncol = 2, nrow = 1, widths = c(1,1.55)) -> left_panel
```


```{r fig.height=3, fig.width=4, message=FALSE, warning=FALSE}
library(ggplot2)
source(source_path)
optimality_values$`Node type`





optimality_values_filtered <-  optimality_values %>% filter((`Node type`== 'Astrocyte' & value >  Astrocyte_cutoff[[3]]) | (`Node type`== 'Neuron' & value > Neuron_cutoff[[3]])  ) %>% dplyr::filter(ID!='AA_H2Ot_neuron')

ggplot(optimality_values_filtered, aes(x= reorder(ID, value),  y= value, fill = variable)) + 
  geom_bar(stat='identity') + 
  #facet_wrap(~Node, dir = "v") + 
   facet_grid(. ~ `Node type`) +
  theme(strip.text.x = element_text(size = 8), axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=7),legend.title = element_blank(),
                                    axis.title.x=element_blank(),axis.title.y=element_blank(),legend.position="right",axis.text.y=element_text(angle=0,hjust=1,vjust=.1,size=4.3),
                                    axis.ticks = element_blank()) +   # Centre plot title
  
  theme(legend.key.height= unit(.25, 'cm'),
        legend.key.width= unit(.32, 'cm'), legend.title = element_blank(), legend.text = element_text(size=8)) +
                              scale_fill_brewer(palette = "Dark2") + coord_flip()  -> optimality #



optimality_panel <- ggarrange(optimality, ncol = 1, nrow = 1 ) %>%  annotate_figure(left = text_grob("Reactions", rot = 90, size = 9), bottom = text_grob("Optimality", rot = 0, size = 9))


```



```{r}
energy_subsystems <- read_delim(file.path(root_path, 'data/energy_subsystems.txt'), delim = "\n", col_names = 'energy_subsystems') %>% 
  mutate(energy_subsystems = str_replace_all(energy_subsystems, '_|-|,', ''))



gene_rxns_whole_NAMU      <- read_csv(file.path(root_path,'data/gene_rxns_whole_NAMU.csv' ))
optimality_values_filtered %<>% mutate(ID = str_replace_all(ID, '_|-|,', '')) 



gene_rxns_whole_NAMU %<>% dplyr::filter(! ID %in% energy_subsystems$energy_subsystems)

Astrocyte_optimal_genes <- gene_rxns_whole_NAMU %>% dplyr::filter(  ID %in% optimality_values_filtered[['ID']]) %>% drop_na() %>% 
                                dplyr::filter(cell =="Astrocyte") %>% .[["gene"]] %>% unique()
Neuron_optimal_genes <- gene_rxns_whole_NAMU %>% dplyr::filter(  ID %in% optimality_values_filtered[['ID']]) %>% drop_na()    %>% 
                                dplyr::filter(cell =="Neuron")%>% .[["gene"]] %>% unique()



write(Astrocyte_optimal_genes,  file.path(root_path,'data/genes_entrez_Astrocyte_optimal_genes.txt'))
write(Neuron_optimal_genes,  file.path(root_path,'data/genes_entrez_Neuron_optimal_genes.txt'))
```





```{r fig.height=3, fig.width=5}
library(clusterProfiler)
library(ReactomePA)
all_optimal_genes <- list(Astrocyte = Astrocyte_optimal_genes, Neuron=  Neuron_optimal_genes)
kk <- compareCluster(all_optimal_genes, fun="enrichMKEGG", pvalueCutoff=1e-3, pAdjustMethod="holm", 
                 qvalueCutoff=1e-3, minGSSize=5, maxGSSize = 30)


dotplot(kk, font.size = 6.1, title = NULL, label_format =65, showCategory = 10, shape = F)+  theme(legend.key.height= unit(.15, 'cm'),
        legend.key.width= unit(.32, 'cm'), legend.title = element_text(size=7), legend.text = element_text(size=4.5)) +
     guides(size = guide_legend(order = 2, 
         keyheight = unit(0, 'inch'))) -> dotplot_kk
```
```{r fig.height=3, fig.width=5}
pp <- compareCluster(all_optimal_genes, fun="ReactomePA::enrichPathway", pvalueCutoff=1e-2, pAdjustMethod="holm", 
                 qvalueCutoff=1e-2, minGSSize=5, maxGSSize = 30)

dotplot(pp, font.size = 6.1, title = NULL, label_format =50, showCategory = 10, shape = F)  +  theme(legend.key.height= unit(.15, 'cm'),
        legend.key.width= unit(.32, 'cm'), legend.title = element_text(size=7), legend.text = element_text(size=4.5)) +
     guides(size = guide_legend(order = 2, 
         keyheight = unit(0, 'inch')))-> dotplot_pp
```


```{r fig.height=8, fig.width=8}

ggarrange(optimality_panel, dotplot_kk, dotplot_pp, nrow = 3, ncol = 1, heights = c(2,1,1.3), labels = c("l","m","n"), vjust = 1.2,  hjust = 0,  font.label =list(size = 11, color = "black", face = "plain", family = NULL) ) -> fba_enrichment_panel

ggarrange(two_left_cols_panel, fba_enrichment_panel, ncol = 2, nrow = 1) -> bottom_panel

bottom_panel
```


```{r fig.height=1.2, fig.width=8}

anls_astro <- magick::image_read_svg(file.path(root_path,'fig_1/anls_astro.svg' ))  %>% as.ggplot
anls_neuron <- magick::image_read_svg(file.path(root_path,'fig_1/anls_neuron.svg' )) %>% as.ggplot
GGC_neuron <- magick::image_read_svg(file.path(root_path,'fig_1/GGC_neuron.svg' )) %>% as.ggplot
GGC_astro <- magick::image_read_svg(file.path(root_path,'fig_1/GGC_astro.svg' )) %>% as.ggplot
sodium_neuron <- magick::image_read_svg(file.path(root_path,'fig_1/sodium_neuron.svg' )) %>% as.ggplot

anls <- ggarrange(anls_astro, anls_neuron, ncol = 2, nrow = 1, align = 'hv', widths = c(1,1), labels = "a", vjust = -.8, hjust = 0,
                  font.label =list(size = 11, color = "black", face = "plain", family = NULL)) %>% 
        annotate_figure(top = text_grob("ANLS", rot = 0, size = 9, vjust = .6, hjust = .5))


ggc <- ggarrange(GGC_neuron, GGC_astro, ncol = 2, nrow = 1, align = 'hv', widths = c(1,1), labels = "b", vjust = -.8, hjust = 0,
                 font.label =list(size = 11, color = "black", face = "plain", family = NULL)) %>% 
        annotate_figure(top = text_grob("GGC", rot = 0, size = 9, vjust = .6, hjust = .5))


na1 <-  ggarrange(sodium_neuron, ncol = 1, nrow = 1, align = 'hv', widths = c(1), labels = "c", vjust = -.8, hjust = 0,
                  font.label =list(size = 11, color = "black", face = "plain", family = NULL)) %>% 
        annotate_figure(top = text_grob("Sodium efflux", rot = 0, size = 8, vjust = .6, hjust = .5))

ggarrange(anls, ggc,  na1,ncol = 3, nrow = 1, align = 'hv', widths = c(1,1.3,.6)) -> objective_panel
objective_panel
```

```{r fig.height=9.2, fig.width=8}
ggarrange(objective_panel, bottom_panel, nrow = 2, ncol = 1, heights = c(1,8)) -> full_panel
```




```{r fig.height=9, fig.width=10}
ggsave(file.path(root_path,'fig_1/full_panel.png' ), full_panel, bg = 'white',dpi = 300, height=9.2, width=8, device = 'png'  )

```












